### PR TITLE
titan: change compression to lzma

### PR DESCRIPTION
**Pull request by Thecrazyskull**
Signed-off-by: Thecrazyskull anaskarbila@gmail.com

### CODE REVIEW

**Comment by luca020400** [comment]
Hmm why ?

**Comment by h2o64** [comment]
Apperently the image is too big.

**Comment by luca020400** [comment]
XZ compression ratio is better then lzma

**Comment by h2o64** [comment]
Fine. It was just a suggestion to fix his size issue

**Comment by Thecrazyskull** [comment]
yup i havent tried xz lol but since it worked with lzma i thought it should be fine.

**Pull request closed without merging**
